### PR TITLE
Feature: log thrown exception

### PR DESCRIPTION
**Pull request by SeriousM**
It's pretty hard to get a clue where in your template an exception was thrown.
The usual way is to test/disable each and every custom method and wait if you got the error.
Or you wrap your output of a method (only if it's a string) with a try/catch and return the exception's message.

This is pretty cumbersome.

I enhanced the logging of the errors in the Parser to log the exception as a whole.

Comparision:

OLD:
```
ERROR: Error rendering template. Cannot get identifier 'getTypeName'. Exception has been thrown by the target of an invocation. Source path: C:\Project\SomeFile.cs
```

NEW:
```
ERROR: Error rendering template. Cannot get identifier 'getTypeName'. Exception has been thrown by the target of an invocation. Source path: C:\Project\SomeFile.cs
System.InvalidOperationException: Oh oh, something happend here. where is the callstack? ---> System.Exception: Inner exception text for demonstration
   --- End of inner exception stack trace ---
   at __Typewriter.Template.getInterfaceName(String name)
   at __Typewriter.Template.getTypeName(Class c)
```
Notice the callstack which really points me the way where the exception was thrown.
`getInterfaceName` and `getTypeName` do exist in my template.

I hope you will accept the PR because it makes it so much easier to find errors.

The modification of the logging only changes the behavior of the Output window, not the errors in the visual studio error list for now.

Should the same error be shown in the error list as well?

### CODE REVIEW

**Comment by frhagn** [comment]
Nice one @SeriousM! 
The TargetInvocationException is probably never be the real error so I guess it would be even better if the inner exception is displayed in the error list as well.

**Comment by SeriousM** [comment]
Ok, done. I also added a hint to look into the output window for stacktrace information.

**Comment by SeriousM** [comment]
Sorry for the spam. I accidentally deleted the branch but I was able to restore it and reopened the PR.

**Comment by frhagn** [comment]
This looks awesome, thanks!

**Comment by SeriousM** [comment]
Thanks!
Am 30.03.2016 15:58 schrieb "Fredrik Hagnelius" <notifications@github.com>:

**Comment by SeriousM** [comment]
may I ask for the next release? I guess after this one I'm done more or less.

**Pull request merged**
