### PR TITLE
Added the ability to differentiate b/t DateTime & DateTimeOffset

### PR DESCRIPTION
**Pull request by youngcm2**

### CODE REVIEW

**Comment by frhagn** [comment]
Hi @youngcm2,
thanks for contributing! 

I like the new feature, but please try to resubmit the PR without changing the indentation of all lines so the actual changes are easier to detect.

**Comment by youngcm2** [comment]
If you add ?w=1 it shows it w/o whitespace differences.

https://github.com/frhagn/Typewriter/pull/139/files?w=1

**Comment by aluanhaddad** [comment]
@youngcm2 That is a github visualization mapping but the files have still been changed. It looks like you are formatting with tabs using an 8 space tab width. Can you reformat the file. In Visual Studio toggle "Ignore Trim WhiteSpace as shown 
image

I want to see this merged as well.

**Comment by frhagn** [comment]
After reviewing this PR again I've decided not to merge it since I don't want to change the current behaviour and make people update their templates when there's a simple way to add this functionality using a custom method inside the template, e.g.

```
${
    bool IsDateTimeOffset(Type type)
    {
        return type.OriginalName == "DateTimeOffset" || type.OriginalName == "DateTimeOffset?";
    }
}
```

**Pull request closed without merging**
