### PR TITLE
Support for referencing external assemblies in template code

### PR DESCRIPTION
**Pull request by rodro75**
Hi @frhagn,

I did my best to follow along your code without changing it too much and I think I have a decent starting point for a PR here :)

You can reference and use any assembly with either an absolute path or a relative one. For example:

`$Reference("D:\Dev\MyAsm.dll")`
`$Reference("tools\MyAsm.dll")`  // relative to the template
`$Reference("~\tools\MyAsm.dll")`  // relative to the project's root
`$Reference("~~\ProjectB\tools\MyAsm.dll")`  // relative to the solution's root.

The new directive must be placed at the beginning of the file.

I'm still not 100% sure about the syntax `$Reference("...")`, I would rather prefer something like `#reference "..."`, what do you think?

Also:
- no support for referencing framework's assemblies yet;
- the renderer loads those assemblies from temp directory, where they are copied, and of course it doesn't release them afterwards. So if you change (recompile?) a referenced assembly then the next render is unable to copy the new file to the temp directory :(

I thought about using a separate AppDomain for the rendering process, but I wanted your feedback before embarking in such a big change.

Let me know,

-Rodrigo-

### CODE REVIEW

**Comment by agustinbcu01** [comment]
Nice Job. 
The hack is the only think that bother me. 
Should be nice have a unit test to keep the eye on that property if changes.

**Comment by frhagn** [comment]
Hi @rodro75,
This looks awesome, thanks for contributing!
I'm away on vacation for a few days, but I'll have a look at this as soon as I have access to my computer again.

**Comment by pbarranis** [comment]
@rodro75 I just wanted to give a huge thanks for contributing this!  I just started using Typewriter a couple weeks ago, and I want to have my enums available in Typescript so I can have them as drop-downs in the UI.  Well, that requires having the human-readable version of the enum values, which requires calling [Humanize() on the enum](https://github.com/Humanizr/Humanizer#humanize-enums).

Without what you've done here, I'd have to write quite a ugly solution!  So again, many thanks!

And @frhagn, it should go without saying that Typewriter rocks!!  :)

**Comment by rodro75** [comment]
@luizfbicalho If you are comfortable with using a beta version you could clone my repo and build the `AssemblyRef` branch using VS 2017, then install the VSIX package that is produced by the build process. You should probably uninstall any previous version first. However, if you're not in a hurry it's better to wait for the final version once it gets merged.

@pbarranis and @agustinbcu01  I'm glad you like it!
Yes, it would be better to write a unit test to keep an eye on that hack, I'll see what I can do.
As a fallback option we could also recursively iterate on DTE's projects in order to find the template's  `ProjectItem` given its file path, but that would happen litterally on every keystroke and it looks like a bad idea performance-wise.

@frhagn Looking forward to hear from you when you come back!

**Comment by luizfbicalho** [comment]
Thanks @rodro75, great work on this , I'll try your branch.

 Do you have any example on loading dlls and including templates in other templates?

**Comment by rodro75** [comment]
@luizfbicalho Template inclusion is another feature I'm working on, but it's not ready yet.
For examples on loading dlls please have a look at the top of this thread.

Additionally, you can now reference GAC assemblies by providing their fully qualified name.
E.g. `$Reference("System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089")`

**Comment by luizfbicalho** [comment]
@rodro75 Can I help with the tenplate inclusion?

**Comment by Beej126** [comment]
Apologies for being dense, does this also address [issue #232](https://github.com/frhagn/Typewriter/issues/232)?

**Comment by rodro75** [comment]
@Beej126  This addresses **only** issue #232.

**Comment by Beej126** [comment]
shucks, reading on phone over the holiday, i just totally missed that obvious issue link further up in the thread... let's delete these superfluous comments after we both read.

thanks for the new awesome sauce!

**Comment by agustinbcu01** [comment]
So far working as expected, there is any way to debug the external Assembler, I tried attaching at the Visual studio instance.

**Comment by rodro75** [comment]
Hi @frhagn ,

I changed the code so that we will try the hacky way first, which is much quicker, then fall back to `Dte.Solution.FindProjectItem` in case the hack won't work anymore in a future version of VS.

Regarding the syntax: 
I changed `$Reference(...)` to `#reference "..."` as it feels more like a directive, but I left it at the file level for now. The reason is that I'm also working on another feature that brings in the possibility to include other files (template partials, .tstp), which comes with its own `#include "..."` syntax that clearly doesn't belong to a code block. I think that having different places for the two directives would be confusing.

One more thing: I'd really like to have the directive in some color other than black and possibly have it in the autocomplete menu, but I couldn't manage to do that. Can you give me any guidance on that?

@agustinbcu01 Good questions! Especially n.2...
I need some time to figure that out. In the meantime you could proxy the required methods in the regular code block.

**Comment by agustinbcu01** [comment]
Yes I'm using xunit to test my external assembler, but should be nice debug a real template rendering.
And also the option of unload the assembler. 
can be something like #reference "xx.yyy.dll" --unload.

**Comment by rodro75** [comment]
@agustinbcu01 
Unfortunately it's not possible to unload an assembly once it's been loaded by the CLR. The only way is to unload the whole AppDomain, i.e. close Visual Studio.

Logging would be really useful though, I'll see what I can do and start a separate PR for that.

**Comment by frhagn** [comment]
@rodro75 
Ok cool, I'll take a look at getting colorization and autocomplete for import statements!

Just so you know regarding includes: I'm working on a new version of Typewriter and for that version I've decided not to support template includes, instead templates can define public extension methods which are available to the other templates. The new version will also support inline templates within c# code which makes it easier to reuse template parts. The syntax will look someting like this:
```
public static string TestExtension(this Class c)
{
    return $[This is template code $c.Name];
}
```
I'll post some more info about this very soon :)

**Comment by frhagn** [comment]
@rodro75 
I've added autocompete and syntax coloring. The new version (1.19.0) is published, finally :)
Thanks again for contributing, really nice work!

**Comment by rodro75** [comment]
@frhagn Cool!

I won’t waste time on template inclusion then. 

It’s been fun to work on this project.
I can’t commit too much time on it, but let me know if you need help with anything ok?

Keep up the great work!

Ciao

**Comment by Sc0tTyXL** [comment]
Was trying to figure out why and how you'd use this but the documentation hasn't been updated yet.

**Comment by PoyangLiu** [comment]
@Sc0tTyXL, you can create a csproj call `MyTypewriterHelper.csproj`.  a public static class `MyTypewriterHelper` with static method of `string GetImports(Class c) { ... }`.

In the template, do something like this, where the double tilda is the solution directory.  or use single tilda for project directory.
```
// tslint:disable
// This file is auto-generated. Do not modify.
#reference "~~\Path\Relative\To\Solution\MyTypewriterHelper.dll"
${
    using Typewriter.Extensions.Types;
    using MyTypewriterHelper;  // the namespace of your project

    Template(Settings settings) { settings.IncludeCurrentProject(); }

    string PrintTimestamp(File f) => string.Format("// Generated on {0:yyyy-MM-dd HH:mm:ss tt}", DateTime.Now);
    string Imports(Class c) => String.Join(Environment.NewLine, MyTypewriterHelper.GetImports(c));

}$PrintTimestamp
$Classes($HasExportToTypeScriptAttribute)[
$Imports

export interface $Name$TypeParameters$Inherit {
    $Properties[
    $Readonly$Name$Optional: $Type;]
    $Methods[
    $Name($Parameters[$name: $Type, ]): $Type;]
}]
```

**Comment by ReactiveThings** [comment]
@PoyangLiu Do you know how to reference Typewriter.CodeModel.dll from MyTypewriterHelper?
When I add reference to Typewriter.CodeModel.dll then typewriter doesn't generate code at all.

**Comment by agustinbcu01** [comment]
For now I build the code model local in my computer. 

Should be nice having  nuGet package to reference the code model, or register it on the GAC. Also unload the referenced assembler will be nice. Today we need to close the   Visual studio to update the external dll.

**Comment by PoyangLiu** [comment]
One thing that I learn, is that you can't use extension method.  It somehow causes my helper project to not load properly.

For example, this does not work for me
``` public static string PrintDebug(static Class c)```
but this does
``` public static string PrintDebug(Class c)```

Let me put up a dumb-down version of my helper repo.  It'll probably answer lots of questions.

**Comment by PoyangLiu** [comment]
Check out the [test repo](https://github.com/PoyangLiu/TypewriterExperiment).
There are two solution, one is a typewriter helper for adding custom methods, the other is the actual app that make use of the typewriter helper.
Hopefully this will help those that have trouble with this.

**Comment by ReactiveThings** [comment]
@PoyangLiu Without extension methods it works like a charm. Thank you for quick help.

**Comment by PoyangLiu** [comment]
@ReactiveThings.  I just noticed my rookie mistake.  The namespace of my helper classes is "namespace MyTypewriterHelper".  It needs to be "namespace Typewriter.CodeModel" for extension method to work.  Updated example repo.

**Comment by Merp4** [comment]
I've just been trying out this functionality, I'm finding once I use the "#reference(...)" syntax the DLL it's referencing becomes locked until VS is closed, which means I can't build my library with extensions in for any changes I make without closing everything down each time.
This also occurs in the example test repo @PoyangLiu linked above.

Can anyone advise if there's a workaround/solution for this situation? Or should I raise a new issue etc?

In case it's relevant I've noticed in my project if I then comment out the line with the "#reference(...)" syntax in, I don't get any errors against lines using my custom extension methods but it appears Typewriter stops processing that template altogether. I seemed to lose the Typewriter option from the output window in this scenario (maybe unrelated) and couldn't find any error output anywhere, I'd expected to get an error about my extension method being unknown etc. but all appears as though it were error-free.

**Comment by Beej126** [comment]
this is of course self promotion but these pain points fall away when you shift to [external CLI  approach](https://github.com/frhagn/Typewriter/issues/293)

**Comment by rodro75** [comment]
Hi @Merp4,
unfortunately there is a big problem with assembly unloading in .net framework: it can’t be done, unless you take care of loading the assembly in a separate AppDomain.
Now, TypeWriter is kinda split in two: there is the rendering code which runs every now and then, and there is the editor/intellisense code, which runs... continuously! Really: on each and every keystroke on the .tst everything needs to be reanalyzed.
The former could be reworked so that it ran in its separate AppDomain, but as far as I know that’s not the case with VS integration code, at least without a massive rewrite.
@frhagn told me that he was already going to rewrite the whole thing anyway, so I didn’t go further than that.

BTW: it looks like he’s almost ready with v2, so stay tuned!

**Comment by Merp4** [comment]
Hi @rodro75 
Thanks for the response, I understand the VS integration stuff can be a pain to work with. I tried having a go at loading them in to another AppDomain (reading your comment I'm thinking it's the rendering portion I've been fiddling with) which I at least think I almost had working, but I've had to abandon it for now. I might have another go at it but it sounds like I'm only tackling the easy half of the problem anyway.

As an aside, I did for a while have a template loading an assembly up for getting values for enums in an attribute value array that didn't seem to lock up the file. I guess it's not the same though since being inside the template being rendered means it seems to dispose properly somewhere since it's a separate on-the-fly thing rather than integrating with the functionality of the template, where the VS extension needs the assemblies loaded for analysis etc.

Looking forward to V2, hope we don't have to wait too long :)

**Pull request merged**
