### PR TITLE
make ko.observable* calls include generic type

### PR DESCRIPTION
**Pull request by jamesmanning**
Without this, I was getting failures - seems to make sense to include the generic type parameter for both in any case.

http://i.imgur.com/Ty3mwgK.png

### CODE REVIEW

**Comment by aluanhaddad** [comment]
The `Object` type should not be used in TypeScript.

**Comment by jamesmanning** [comment]
@aluanhaddad I apologize if I'm misinterpreting your comment, but I agree.  Are you agreeing that this is a good change or saying it's a problem?

The current behavior is that the construction doesn't pass a generic type param, so it's effectively passing a generic type parameter of `Object` and this PR is to fix that by passing the expected type.

Just wanted to check since I just wanted to make sure the error message from my screenshot wasn't getting misinterpreted as my change switching it *to* a generic type param of `Object` instead of away from that. 😄

**Comment by aluanhaddad** [comment]
Sorry, I think I misunderstood the purpose of your PR. I was just remarking that `Object` indicates a problem. Better to use `any` or `{ [key: string]: any }` if the only other option is `Object`. I think your change looks good!

**Comment by frhagn** [comment]
Hi @jamesmanning,
this looks great, merging now.. Thanks for helping out!

**Pull request merged**
