### PR TITLE
Concurrency fixes

### PR DESCRIPTION
**Pull request by coolkev**
I have been noticing some serious performance issues in VS 2015, and it has been freezing up regularly as well. I believe the previous EventQueue timer code may be the cause, and have updated it to use a BlockingQueue instead. I also made the Template save events fully asynchronous.

I have been running this version with my changes on several of my projects for the past few weeks and it is very stable and runs much faster.

### CODE REVIEW

**Comment by frhagn** [comment]
@coolkev, this looks amazing!

Have you done any testing on VS 2013? Much of the wierd timing/lock code in the old EventQueue is there because of issues with CodeDom when donig multi-file refactoring. But since the parallel rendering is removed theese issues might be gone as well..
Any way, I'd like to do some more testing, but it's defenetly a huge step forward so if there aren't any big issues in VS 2013 I'll merge this right away.

Great work, thanks for sharing it :)

**Comment by coolkev** [comment]
@frhagn, I have not tested in VS 2013. I'll try and do some testing on it this week.

**Comment by coolkev** [comment]
@frhagn, I tested this in VS 2013, and it seems to be working fine to me.

**Comment by frhagn** [comment]
@coolkev, that sounds great! I've been testing this as well, and I'm having some issues when renaming classes and properties using ReSharper that modifies multiple files. Have you used ReSharper, and if so, have you experienced any similar issues?

I'm looking at this issue and I hope to be able to merge you PR soon, but I'd like ho resolve this issue first.

**Comment by coolkev** [comment]
@frhagn, I do use resharper (v9.2) and VS 2015 and I have not noticed any issues with modifying multiple files. I just tried the following tests and everything worked as expected for me:
 - multiple classes in a single file: Move types to matching files in folder
 - right click folder - Refactor - Move types to matching files 

What is the issue that you are seeing? And are you able to reproduce it consistently?

**Pull request merged**
