### PR TITLE
Added option feature to don't render the template when a file is saved.

### PR DESCRIPTION
**Pull request by JulioGold**
Added option feature to don't render the template when a file is saved.

typewriter options

#86

### CODE REVIEW

**Comment by frhagn** [comment]
Hi @JulioGold, this looks great!
One question, does this setting default to True or False?.. It's important that auto rendering is enabled by default.

**Comment by JulioGold** [comment]
Hi @frhagn 
It's just a C# bool, therefore default is false.
I think is better because is so boring when we working at a project with a lot off classes, it's turn the project very very slow, each save file is extremely inconvenient.
The people can render the template just by clicking with the right button at the .tst file and choose the option `Render Template`, at this way you can render just the templates wich you really want and at the time you really need to render the template, don't losing time on each save file.
rendertemplate

IF you think it's really convenient, it's possible just setting up the property `RunOnFileSave` at the class `TypewriterOptionsPage` to `true` by default.
It's can by made with `[System.ComponentModel.DefaultValue(true)]` annotation.

Thank's

**Comment by frhagn** [comment]
Perfect, thanks.
I think it needs to be true by default so it doesn't change behavior when people install the update..

**Comment by LeeCheneler** [comment]
+1 for being default false, everyone I know who uses this loves the tool, but hates that you cant turn on render on save, no one working on anything but a tiny project will want it default to true, and auto gen stuff is more of a big project tool, that's where you see the most gains.

**Comment by frhagn** [comment]
Do you mean that auto render should be disabled when saving tst files or when saving c# files?

**Comment by LeeCheneler** [comment]
Both, we think there should be a setting for each and that it should be off for both by default.

**Pull request merged**
