### PR TITLE
Get constant's value

### LINKED ISSUE #101: Get constant's value
Is it possible to get the value of an constant like for the enum with `.Value`?

### PR DESCRIPTION
**Pull request by SeriousM**
see #101
closes #101

### CODE REVIEW

**Comment by SeriousM** [comment]
the commit message `	Added the struct's initial value` is wrong, it's about the constant's initial value.. my bad

**Comment by SeriousM** [comment]
btw @frhagn, your code is very clean :+1:

**Comment by frhagn** [comment]
Thanks @SeriousM, this looks great!

**Comment by SeriousM** [comment]
may I ask for the next release date? :)

**Comment by mcgri** [comment]
Hi Guys,
Just a note. The functionality works great,however, the documentation page needs to be updated to include "Value" property at the Constant's description. 

http://frhagn.github.io/Typewriter/pages/documentation.html

**Pull request merged**
